// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDTQBwOJVO4tR18hverTBXxwWT6D4iCUU',
    appId: '1:782956789905:web:c6e6c5ef5aab9fa95f7f30',
    messagingSenderId: '782956789905',
    projectId: 'flutterapp-c2a2e',
    authDomain: 'flutterapp-c2a2e.firebaseapp.com',
    storageBucket: 'flutterapp-c2a2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNSxAbXOnNVF4J6zimLqA9SXbyCTconM',
    appId: '1:151967801739:android:e3ad4529f9dd789d1e0f8e',
    messagingSenderId: '151967801739',
    projectId: 'licesne-f75d8',
    storageBucket: 'licesne-f75d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjk9752a5vpDbE9PNo1_bQVK4IN8iz3Ik',
    appId: '1:151967801739:ios:9a1c7e5279ae001c1e0f8e',
    messagingSenderId: '151967801739',
    projectId: 'licesne-f75d8',
    storageBucket: 'licesne-f75d8.firebasestorage.app',
    iosBundleId: 'com.example.checkLicense',
  );

}